/* generated by JSetup v0.95 :  at 04/06/2018 22:50:19 */
define(function(require) {
	var Backbone = require('adapters/backbone-adapter');

	var MovieModel = Backbone.Model.extend({
		urlRoot : 'http://209.239.124.224:8080/movieapp/rs/crud/movies',

		credentials : {
			username : 'robsonmrsp',
			password : '123456'
		},

		defaults : {
			id : null,
			plot : '',
			title : '',
			year : '',
			type : '',
			genre : '',
			poster : '',
			budget : '',
			releaseDate : '',
		}
	});

	return MovieModel;
});
